export const ErrorCodes = {
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  NO_CREDIT_BALANCE: "NO_CREDIT_BALANCE",
  NO_CREDIT_RESET: "NO_CREDIT_RESET",
  CUSTOMER_HAS_ORDERS: "CUSTOMER_HAS_ORDERS",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  NO_AMOUNT_DUE: "NO_AMOUNT_DUE",
  DELIVERY_PAYMENT_REQUIRED: "DELIVERY_PAYMENT_REQUIRED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  DEFAULT_TAGS_LOCKED: "DEFAULT_TAGS_LOCKED",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  PRODUCT_IN_USE: "PRODUCT_IN_USE",
  SESSION_REQUIRED: "SESSION_REQUIRED",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  WRONG_CREDENTIALS: "WRONG_CREDENTIALS",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  INVALID_SESSION: "INVALID_SESSION",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  WRONG_CURRENT_PASSWORD: "WRONG_CURRENT_PASSWORD",
  PASSWORDS_REQUIRED: "PASSWORDS_REQUIRED",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_UNCHANGED: "PASSWORD_UNCHANGED",
  AUTH_NETWORK: "AUTH_NETWORK",
  AUTH_REQUEST_FAILED: "AUTH_REQUEST_FAILED",
  LOGIN_FAILED: "LOGIN_FAILED",
  LICENSE_SERVER: "LICENSE_SERVER",
  LICENSE_EMPTY_RESPONSE: "LICENSE_EMPTY_RESPONSE",
  LICENSE_VERIFY_FAILED: "LICENSE_VERIFY_FAILED",
  PRINT_FRAME_FAILED: "PRINT_FRAME_FAILED",
  PRINT_POPUP_BLOCKED: "PRINT_POPUP_BLOCKED",
  DB_SESSION_REQUIRED: "DB_SESSION_REQUIRED",
  GENERIC: "GENERIC",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AppError extends Error {
  readonly code: ErrorCode;

  constructor(code: ErrorCode) {
    super(code);
    this.name = "AppError";
    this.code = code;
  }
}

export function isAppError(err: unknown): err is AppError {
  return err instanceof AppError && typeof err.code === "string";
}
